sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
before_install:
  - npm i -g npm@^6.0.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn install --force
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
